import Footer from "@/components/sections/Footer";
import Header from "@/components/header/Header";
import { Inter } from "next/font/google";
import { AnimatePresence } from "framer-motion";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "An aesthetic room is given harmony",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AnimatePresence mode="wait">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </AnimatePresence>
    </html>
  );
}
